name: web
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
